name: Deploy to Amazon EC2

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Git pull and run Docker on EC2
      id: deploy
      uses: appleboy/ssh-action@master;
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          sudo yum install -y git
          sudo yum install -y docker
          DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
          mkdir -p $DOCKER_CONFIG/cli-plugins
          curl -SL https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
          git clone https://github.com/Nalexx6/Diploma.git
          cd Diploma/infrastructure/kafka
          docker-compose up -d
    
