name: Deploy to S3

on: 
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out
      uses: actions/checkout@v3
      
    - name: prepare-env
      run: | 
        pip3 install boto3 --user
        export AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}
        export AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}
      shell: sh

    - name: deploy
      run: python3 deployment/deploy.py --s3-bucket ${{secrets.S3_BUCKET}} --s3-object-path ${{secrets.S3_OBJECT_PATH}}
      shell: sh
