name: Deploy Metabase

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker pull and run on EC2
      id: deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.METABASE_EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          sudo yum install -y docker
          sudo systemctl start docker
          sudo docker run -d -p 3000:3000 --name metabase metabase/metabase

